name: Pilipala Rolling Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'

jobs:
  android:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.vars.outputs.short_sha }}
    steps:
      - name: 代码迁出
        uses: actions/checkout@v4

      - name: 获取短 Commit SHA
        id: vars
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: 构建Java环境
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: 检查缓存
        uses: actions/cache@v3
        id: cache-flutter
        with:
          path: /root/flutter-sdk
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}

      - name: 安装Flutter
        if: steps.cache-flutter.outputs.cache-hit != 'true'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.41.6
          channel: any

      - name: 下载项目依赖
        run: flutter pub get

      - name: 解码生成 jks
        run: echo $KEYSTORE_BASE64 | base64 -di > android/app/vvex.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Flutter Build APK (Split)
        run: flutter build apk --release --split-per-abi
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}

      - name: Flutter Build APK (Universal)
        run: flutter build apk --release
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}

      - name: 重命名应用
        run: |
          for file in build/app/outputs/flutter-apk/app-*.apk; do
            if [[ $file =~ app-(.*)-release\.apk ]]; then
              arch="${BASH_REMATCH[1]}"
              mv "$file" "build/app/outputs/flutter-apk/Pili-rolling-${arch}.apk"
            elif [[ $file == *"app-release.apk" ]]; then
              mv "$file" "build/app/outputs/flutter-apk/Pili-rolling-universal.apk"
            fi
          done

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: Pilipala-Rolling-Artifacts
          path: build/app/outputs/flutter-apk/Pili-rolling-*.apk
          retention-days: 3

  upload_release:
    runs-on: ubuntu-latest
    needs: [android]
    permissions:
      contents: write
    steps:
      - name: 下载全部产物
        uses: actions/download-artifact@v4
        with:
          name: Pilipala-Rolling-Artifacts
          path: ./Release-Files

      - name: 发布 Rolling 版本
        uses: ncipollo/release-action@v1
        with:
          tag: "rolling"
          name: "Rolling Build"
          body: |
            这是最新的代码滚动构建版本。
            **当前提交**: `${{ github.sha }}`
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          prerelease: true
          replacesArtifacts: true
          artifacts: "Release-Files/*"
